# Generated by Django 3.1.4 on 2021-02-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='isim')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='email')),
                ('meslek', models.CharField(choices=[(None, 'Lutfen Bir Meslek seciniz'), ('Öğretmen', 'ögretmen'), ('Muhendis', 'muhendis'), ('Doktor', 'doktor'), ('polis', 'polis'), ('Diger', 'diger')], max_length=100, null=True)),
                ('mesaj', models.TextField(max_length=300, null=True, verbose_name='mesaj')),
            ],
            options={
                'verbose_name_plural': 'Gelen Formlar',
            },
        ),
    ]
